
MPICC = mpicxx

all 		:	ejer1 ejer2 ejer3 ejer4

ejer1 :	
	$(MPICC)  -o ejercicio1 ejercicio1.cpp
ejer2 :	
	$(MPICC)  -o ejercicio2 ejercicio2.cpp
ejer3 :	
	$(MPICC)  -o ejercicio3 ejercicio3.cpp
ejer4 :	
	$(MPICC)  -o ejercicio4 ejercicio4.cpp